[meta]
name     = "TrackGenerator"
author   = "AvondaleZPR"
category = "Map Editor"
version = "0.9.2"
siteid = 156

[script]
imports = [ "Icons.as", "Formatting.as", "Permissions.as" ]

timeout = 15000